- src/nfd_win.cpp
This PR converts '/' to '\\' for the `defaultPath` parameter on Windows (when using the UTF-8 version of the APIs).  This ensures consistent functionality on Windows and Unix.  For the native Windows (wchar) version of the APIs, this transformation is not done - those who use the native Windows version already would have written Windows-specific code, and hence cross-platform consistency would not be a concern.
Resolves #8.
> Normalize path separator on Windows

- src/nfd_gtk.cpp
Didn't compile on Ubuntu 16.04 due to missing include for <stdlib.h>, resulting in error messages that malloc and free are not defined.
I'm unsure why this isn't a problem on Ubuntu 18.04.
> Include <stdlib.h> for malloc and free.

- .github/workflows/cmake.yml
This should ensure that compilation problems on Ubuntu 16.04 (like #10) never arise again.
> GitHub Actions: Run multiple Ubuntu versions

- .github/workflows/cmake.yml
- README.md
- src/nfd_gtk.cpp
Fix Linux GCC warnings, and compile for GCC and Clang with `-Werror`.  Resolves #5.
> Fix Linux GCC warnings

- CMakeLists.txt
Currently, the test targets are always built. This change adds a flag for that, so they aren't built when used from another cmake project by default.
> Add flag for building tests

- src/include/nfd.h
- src/nfd_cocoa.m
- src/nfd_gtk.cpp
- src/nfd_win.cpp
- test/CMakeLists.txt
- test/test_opendialogmultiple_enum.c
Benefits:
- Nicer API for use with C++ and Rust iterators
- O(N) instead of O(N^2) retrieval of paths
> Implement enumerator (aka iterator) for PathSet

- src/include/nfd.h
In nfd.h the line commented out line `/* nfd_<targetplatform>.c */` seems to serve no purpose, especially considering the target plattform is configured at buildtime.
> Remove seemingly forgotten line

- README.md
To build under MSYS2 + MinGW64 with `-lcomctl32 -luuid` fails with `undefined reference to `__imp_CoInitializeEx` and similar linking errors.
```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\cc4PrAbe.ltrans0.ltrans.o:C:/msys64/home/Bayonetta2.0/new-horizon/lbs/nativefiledialog-extended/src/nfd_win.cpp:309: undefined reference to `__imp_CoInitializeEx'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\cc4PrAbe.ltrans0.ltrans.o:C:/msys64/home/Bayonetta2.0/new-horizon/lbs/nativefiledialog-extended/src/nfd_win.cpp:340: undefined reference to `__imp_CoCreateInstance'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ …
```
> README: Fix Windows link dependencies

- .github/workflows/cmake.yml
- README.md
- src/CMakeLists.txt
- src/include/nfd.h
- src/nfd_portal.cpp
This PR is an alternative implementation for Linux, that uses [xdg-desktop-portal](https://flatpak.github.io/xdg-desktop-portal/) so that the "native" file dialog is displayed.  (In practice, this is either GTK or KDE; xfce doesn't have a portal backend implementation.)  It makes D-Bus API calls directly.  This should work if the user has xdg-desktop-portal and a suitable backend (either xdg-desktop-portal-gtk or xdg-desktop-portal-kde) installed (which apparently is the case for all common desktop Linux distributions), but will fail with NFD_ERROR otherwise.
This implementation links with D-Bus (dbus-1) instead of of GTK (gtk+-3.0).
Closes #24.  Also refer to https://github.com/mlabbe/nativefiledialog/issues/40.
> Implement D-Bus portal backend

- .circleci/config.yml
- .github/workflows/cmake.yml
- README.md
- src/CMakeLists.txt
- src/nfd_cocoa.m
The `allowedFileTypes` property is deprecated on MacOS >= 12.0, and will probably be removed in the future.  This PR makes NFD use the `allowedContentTypes` property on MacOS >= 12.0 (using a runtime check if necessary, because old versions of MacOS may not have the UniformTypeIdentifiers library needed for `allowedContentTypes` to work).
This may be a breaking change on MacOS >= 12.0 for projects that use custom file extensions. If that is the case, an `Info.plist` file needs to be added to the app to define the custom file extension, as per [the Apple documentation](https://developer.apple.com/documentation/uniformtypeidentifiers/defining_file_and_data_types_for_your_app?language=objc). Going forward, the `allowedFileTypes` property will probably be removed, so this will eventually be …
> MacOS: Use allowedContentTypes on >=12.0 instead of allowedFileTypes

- README.md
This uses the new GitHub feature to [choose an image to display depending on the theme](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to).
> README: Add dark mode images

- .github/workflows/cmake.yml
- src/CMakeLists.txt
- src/nfd_portal.cpp
Automatically appending the file extension breaks portals because the overwrite prompt will check the wrong file, and the wrong file will be exposed to the sandboxed application.
> Portal: Don't automatically append file extension in SaveDialog()

- src/CMakeLists.txt
I added the current source dir to target_include_dir.
This get the include path to be correctly identified when this lib is used.
> Build: Set target_include_directories correctly when NFDe is added as a subdirectory

- .github/workflows/cmake.yml
ClangFormat 14 formats this code incorrectly:
```
diff --git a/src/include/nfd.hpp b/src/include/nfd.hpp
index bbce108..21c4e1[5](https://github.com/btzy/nativefiledialog-extended/actions/runs/3893292193/jobs/6645716907#step:4:6) 100[6](https://github.com/btzy/nativefiledialog-extended/actions/runs/3893292193/jobs/6645716907#step:4:7)44
--- a/src/include/nfd.hpp
+++ b/src/include/nfd.hpp
@@ -151,[7](https://github.com/btzy/nativefiledialog-extended/actions/runs/3893292193/jobs/6645716907#step:4:8) +151,[9](https://github.com/btzy/nativefiledialog-extended/actions/runs/3893292193/jobs/6645716907#step:4:10) @@ class Guard {
}
}
#endif
-    inline ~Guard() noexcept { Quit(); }
+    inline ~Guard() noexcept {
+        Quit();
+    }
// Not allowed to copy or move this class
Guard(const …
```
> ClangFormat: Force ClangFormat 13 for now

- src/CMakeLists.txt
When gtk or dbus is installed on a non default location, for instance /usr/local for *BSD,
using XXX_LIBRARIES failed at link phase, while XXX_LINK_LIBRARIES always works.
> Build: Use XXX_LINK_LIBRARIES for linking to support *BSD

- src/nfd_portal.cpp
When compiling against a version of GLIBC before 2.25, `getrandom` is not available, so this change provides a fallback to perform the relevant syscall directly.
> Add `getrandom` fallback for versions of GLIBC < 2.25

- .github/workflows/cmake.yml
GitHub Actions no longer supports Ubuntu 18.04 runners.  Since `ubuntu-latest` refers to Ubuntu 22.04, we don't currently test on Ubuntu 20.04, so we'll upgrade the Ubuntu 18.04 runners to Ubuntu 20.04.
> CI: Upgrade Ubuntu 18.04 to Ubuntu 20.04

- README.md
Portals are now fairly well-tested by a variety of users of NFDe.
A link is now also added to https://github.com/flatpak/xdg-desktop-portal/pull/874 that adds support for setting a default folder in the OpenFile() method.
> README: Remove untested portal warning and link OpenFile() current_folder PR

- src/nfd_portal.cpp
It is not always possible to provide a good error message with a hardcoded string, because additional runtime information might be useful.  This PR adds `NFDi_SetFormattedError()`, that can be used in place of `NFDi_SetError()` and calls `vsprintf()` internally.
> Portal: Support formatted error messages using sprintf()

- .github/workflows/cmake.yml
- src/CMakeLists.txt
- src/include/nfd.h
If CMake is configured to create a shared library (.dll) for this library, the symbols (function names) are not exported and an empty dll file is created.
On Windows, the compiler has to be invited explicitly by the programmer to export (or import) a function from a shared library (e.g. using `__declspec(dllexport)` attributes...
It is common to define a LIBRARY_NAME_API macro for this purpose and prefix it to any publicly visible function declaration.
This PR adds support for this convention.
> Add support for building shared libraries on Windows

- .github/workflows/cmake.yml
Clang is unable to compile some libstdc++ headers in C++23 mode.
> CI: Downgrade from C++23 to C++20 on Ubuntu

- CMakeLists.txt
Support for CMake versions lower than 3.5 have been deprecated with the newer versions of CMake. Thus a warning is being printed to the console now when configuring projects that use nativefiledialog-extended:
```
CMake Deprecation Warning at lib/third_party/nativefiledialog/CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
```
This PR updates the minimum required cmake version to 3.5. Seeing that this version came out almost 8 years ago, this shouldn't affect most projects depending on this library.
> Update minimum cmake version to 3.5

- src/include/nfd.h
- src/nfd_cocoa.m
- src/nfd_gtk.cpp
- src/nfd_portal.cpp
- src/nfd_win.cpp
This pull request is intended to address issues with creating wrappers in other languages. I made Utf8 function exports available on all platforms.
Supercedes #118 
Resolves #117
> Replace Macros with Aliases

- README.md
CMake's configure command generates all profiles for MSVC, and you need to choose the correct profile at build time.
Resolves #130.
> README: Fix build command for MSVC

- src/include/nfd.h
- src/include/nfd.hpp
- src/nfd_cocoa.m
- src/nfd_gtk.cpp
- src/nfd_portal.cpp
- src/nfd_win.cpp
- test/CMakeLists.txt
- test/test_opendialog_native_with.c
- test/test_opendialog_with.c
- test/test_pickfolder_native_with.c
- test/test_pickfolder_with.c
- test/test_savedialog_native_with.c
- test/test_savedialog_with.c
This PR adds a new API function for each of the four kinds of dialogs, which take in a versioned struct.  The version is set by an inline function in nfd.h, and the library checks the version to determine the number of fields in the struct.  Additional fields can then be added to the end of the struct without breaking forward compatibility (binary built with an older version of NFDe works with a newer version of NFDe) or backward compatibility (automatically by ignoring the additional fields).
This will allow new options to be added without breaking forward compatibility, which will make #90, #93, #99, and #126 implementable.
Resolves #92.
> Add versioned API

- .github/workflows/cmake.yml
- CMakeLists.txt
- src/CMakeLists.txt
- src/include/nfd.h
- src/include/nfd.hpp
- src/include/nfd_glfw3.h
- src/include/nfd_sdl2.h
- src/nfd_cocoa.m
- src/nfd_gtk.cpp
- src/nfd_portal.cpp
- src/nfd_win.cpp
- test/CMakeLists.txt
- test/test_sdl.c
- test/test_sdl.manifest
On at least Windows and Linux (both GTK and Portal), the dialog misbehaves in a noticeable way when the parent window handle is not passed to the underlying platform-specific API.  The macOS (Cocoa) backend guesses the parent from the key window (the window receiving keyboard events).  The parent window handle, however, is platform-specific (and on Linux, also specific to the windowing system) (e.g. `HWND` on Windows, `NSWindow*` on macOS, `Window` on X11, `wl_surface*` on Wayland), which means that NFDe necessarily needs to expose an API that is not fully platform-agnostic, if it is to allow users to pass it the parent window handle.
This is acceptable if the user is not using any platform abstraction framework (e.g. SDL2 or GLFW), since the user must already be writing platform-specific …
> New feature: Accept native parent window handle and implement glue code to major platform abstraction frameworks

- .github/workflows/cmake.yml
There are warnings in GitHub Actions due to using actions/checkout@v2 and actions/upload-artifact@v2, which are deprecated.  This PR updates them to actions/checkout@v4 and actions/upload-artifact@v4.
GitHub Actions has also deprecated their macOS 11 runner, so this PR removes it too.
Doing these things removes all the warnings.
> CI: Update to actions/checkout@v4 and actions/upload-artifact@v4 and remove macOS 11 job

- src/CMakeLists.txt
Add a target `nfd::nfd` as an alias for the library `nfd`.
This naming convention is common in other CMake projects. The presence of `::` in the identifier results in fail-fast behavior; when a user calls `target_link_libraries` or similar, `nfd::nfd` MUST be an existing target at configure time, but `nfd` might have been a system library. As a result, the latter would appear to work until the linker fails to find a library by that name.
This is not a breaking change - plain `nfd` is still accessible.
> Build: Add alias target for dependent project CMake consumption

- src/nfd_gtk.cpp
Setting the default GdkDisplay doesn't actually cause a newly opened dialog window to use it.  The more correct way seems to be to make the dialog window use the same GdkScreen as the parent.  Each GdkScreen maps to one GdkDisplay, so this guarantees that the dialog window uses the same GdkDisplay as the parent too.
> GTK: Open the dialog window on the same GdkScreen (and GdkDisplay) as the parent

- .github/workflows/cmake.yml
- src/nfd_gtk.cpp
- src/nfd_portal.cpp
> GTK, Portal: Fix variable shadowing warnings

- README.md
- src/CMakeLists.txt
- src/include/nfd.h
- src/nfd_win.cpp
Implements #151 
Implemented using a cmake option with default value set to off.
`src/CMakeLists.txt`
```cmake
option(NFD_OVERRIDE_RECENT_WITH_DEFAULT "Use defaultPath instead of recent folder on Windows" OFF)
if (NFD_OVERRIDE_RECENT_WITH_DEFAULT)
target_compile_definitions(${TARGET_NAME} PRIVATE NFD_OVERRIDE_RECENT_WITH_DEFAULT)
endif()
```
`nfd_win.cpp`
```c++
#ifdef NFD_OVERRIDE_RECENT_WITH_DEFAULT
// Use SetFolder() if you always want to use the default folder
if (!SUCCEEDED(dialog->SetFolder(folder))) {
NFDi_SetError("Failed to set default path.");
return NFD_ERROR;
}
#else
// SetDefaultFolder() might use another recently used folder if available, so the user
// doesn't need to keep navigating back to the default folder (recommended by Windows).
if …
```
> Windows: Add NFD_OVERRIDE_RECENT_WITH_DEFAULT flag

- .github/workflows/cmake.yml
CMake 3.31 passes the `-std` flag to clang-cl, even when compiling C code.  This causes clang-cl to abort.  This PR downgrades Clang in the CI build that uses clang-cl.
> CI: Fix Windows Clang (clang-cl) build

- CMakeLists.txt
Same as https://github.com/btzy/nativefiledialog-extended/pull/113, support for CMake versions lower than 3.10 have been deprecated with CMake 3.31
> Compatibility with versions of CMake older than 3.10 is now deprecated and will be removed from a future version. Calls to [cmake_minimum_required()](https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html#command:cmake_minimum_required) or [cmake_policy()](https://cmake.org/cmake/help/latest/command/cmake_policy.html#command:cmake_policy) that set the policy version to an older value now issue a deprecation diagnostic.
Source: https://cmake.org/cmake/help/latest/release/3.31.html#deprecated-and-removed-features
> Build: Update minimum CMake version to 3.10

- .github/workflows/cmake.yml
- src/nfd_portal.cpp
- test/test_sdl.c
ClangFormat 13 is no longer available on GitHub Actions, so we switch to the newest one, which seems to be ClangFormat 16.
We also fix an over-eager GCC warning in `test_sdl.c`.
> ClangFormat: Use latest version

- src/nfd_gtk.cpp
- src/nfd_portal.cpp
The existing code is technically correct, but using `wchar_t` literals are unintended since we always use UTF-8 on Linux (both GTK and Portal).
> Linux (GTK, Portal): Fix unintended wchar_t literals

- .github/workflows/cmake.yml
Ubuntu 20.04 is being retired from GitHub Actions.
> CI: Switch Ubuntu 20.04 to Ubuntu 22.04
